### PR TITLE
Add node affinity to deploy on amd64 nodes only

### LINKED ISSUE #34: device plugin daemonset tries to load itself on non-amd64 nodes
Resulting in lots of crashes on arm64 nodes:

```
❯ kgpwide | grep Crash
amdgpu-labeller-daemonset-qh2sr           0/1     CrashLoopBackOff   245 (4m3s ago)    20h     10.42.1.74    pirate1    <none>           <none>
amdgpu-device-plugin-daemonset-zqk24      0/1     CrashLoopBackOff   248 (3m52s ago)   20h     10.42.0.98    captain    <none>           <none>
amdgpu-device-plugin-daemonset-vbdkt      0/1     CrashLoopBackOff   248 (3m31s ago)   20h     10.42.2.208   pirate2    <none>           <none>
amdgpu-device-plugin-daemonset-4k988      0/1     CrashLoopBackOff   245 (2m47s ago)   20h     10.42.1.73    pirate1    <none>           <none>
amdgpu-labeller-daemonset-nhlwf           0/1     CrashLoopBackOff   247 (2m33s ago)   20h     10.42.2.209   pirate2    <none>           <none>
amdgpu-labeller-daemonset-bnjcb           0/1     CrashLoopBackOff   248 (31s ago)     20h     10.42.0.99    captain    <none>           <none>
```

### PR DESCRIPTION
**Pull request by agilob**
Prevents crash loop on ARMs

Closes #34

### CODE REVIEW

**Comment by julian3xl** [comment]
from my point of view, you may offer a parameter to add affinities using Values, as all the rest of helm charts, and then add your desired affinities, instead of forcing fixed affinities.

**Comment by y2kenny** [comment]
This is just sample yaml files unrelated to Helm.  @agilob, can you just use a simple nodeSelector with `kubernetes.io/arch: amd64` for this?

**Comment by agilob** [comment]
Ok, I looked into it and _technically_ this change isn't required, as there is `node_selector` in the values.yaml for helm-chart, but I think the default value in the helm-chart should be changed to contain `kubernetes.io/arch: amd64` otherwise it will automatically try to deploy dp, labeller and healthcheck on ARM too

**Comment by agilob** [comment]
I updated this branch with the new suggested default value

**Pull request merged**
